# Generated by Django 4.2.6 on 2023-11-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_order_remove_auction_user_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aucted_product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.bidder'),
        ),
    ]
