# Generated by Django 4.2.6 on 2023-11-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_aucted_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aucted_product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temp',
        ),
        migrations.AlterField(
            model_name='aucted_product',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction_user'),
        ),
    ]
