# Generated by Django 4.2.6 on 2023-11-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_remove_aucted_product_user_remove_product_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aucted_product',
            name='win_ner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction_user'),
        ),
        migrations.AlterField(
            model_name='aucted_product',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
