# Generated by Django 4.2.6 on 2023-11-04 11:01

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_alter_aucted_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='session',
            field=models.DateTimeField(validators=[auction.models.validate_future_datetime]),
        ),
    ]
